# Generated by Django 5.2.7 on 2026-01-04 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_page', '0002_tvshow_alter_movie_options_remove_movie_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TVShow',
        ),
    ]
