# Generated by Django 5.2.7 on 2026-01-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_page', '0003_delete_tvshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
